FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY order_service.py .
COPY redis_db.py .
COPY in_memory_db.py .

EXPOSE 8002

CMD ["uvicorn", "order_service:app", "--host", "0.0.0.0", "--port", "8002"]
