FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY user_service.py .
COPY redis_db.py .
COPY in_memory_db.py .

EXPOSE 8001

CMD ["uvicorn", "user_service:app", "--host", "0.0.0.0", "--port", "8001"]
